export type IntelligenceSectionKey =
  | 'client_profiles'
  | 'competitors'
  | 'search_results'
  | 'images'
  | 'videos'
  | 'news'
  | 'brand_mentions'
  | 'media_assets'
  | 'search_trends'
  | 'community_insights'
  | 'ai_questions'
  | 'web_sources'
  | 'web_snapshots'
  | 'web_extraction_recipes'
  | 'web_extraction_runs';

export type IntelligenceCrudAction = 'read' | 'create' | 'update' | 'delete' | 'clear';

export type IntelligenceSectionConfig = {
  key: IntelligenceSectionKey;
  label: string;
  dataType: string;
  moduleKey?: string;
  summary: string;
};

export const INTELLIGENCE_SECTIONS: IntelligenceSectionConfig[] = [
  {
    key: 'client_profiles',
    label: 'Client Profiles',
    dataType: 'social-profiles',
    moduleKey: 'client_profiles',
    summary: 'Connected social profiles for the client brand.',
  },
  {
    key: 'competitors',
    label: 'Competitors',
    dataType: 'competitors',
    moduleKey: 'competitors',
    summary: 'Discovered and shortlisted competitor entities.',
  },
  {
    key: 'search_results',
    label: 'Search Results',
    dataType: 'search-results',
    moduleKey: 'search_results',
    summary: 'Raw web search results used as research evidence.',
  },
  {
    key: 'images',
    label: 'Images',
    dataType: 'images',
    moduleKey: 'images',
    summary: 'Image SERP records and visual references.',
  },
  {
    key: 'videos',
    label: 'Videos',
    dataType: 'videos',
    moduleKey: 'videos',
    summary: 'Video SERP records and source links.',
  },
  {
    key: 'news',
    label: 'News',
    dataType: 'news',
    moduleKey: 'news',
    summary: 'News article records relevant to the niche.',
  },
  {
    key: 'brand_mentions',
    label: 'Brand Mentions',
    dataType: 'brand-mentions',
    moduleKey: 'brand_mentions',
    summary: 'Web mentions tied to the client brand.',
  },
  {
    key: 'media_assets',
    label: 'Media Assets',
    dataType: 'media-assets',
    summary: 'Downloaded media files and processing metadata.',
  },
  {
    key: 'search_trends',
    label: 'Search Trends',
    dataType: 'trends',
    moduleKey: 'search_trends',
    summary: 'Keyword trend snapshots and related queries.',
  },
  {
    key: 'community_insights',
    label: 'Community Insights',
    dataType: 'community-insights',
    moduleKey: 'community_insights',
    summary: 'Forum/social pain points and demand signals.',
  },
  {
    key: 'ai_questions',
    label: 'AI Questions',
    dataType: 'ai-questions',
    moduleKey: 'ai_questions',
    summary: 'Structured strategic answers generated by AI.',
  },
  {
    key: 'web_sources',
    label: 'Web Sources',
    dataType: 'web-sources',
    moduleKey: 'web_sources',
    summary: 'Canonical web source URLs discovered for this workspace.',
  },
  {
    key: 'web_snapshots',
    label: 'Web Snapshots',
    dataType: 'web-snapshots',
    moduleKey: 'web_snapshots',
    summary: 'Fetched page snapshots and cleaned text payloads.',
  },
  {
    key: 'web_extraction_recipes',
    label: 'Web Extraction Recipes',
    dataType: 'web-recipes',
    moduleKey: 'web_extraction_recipes',
    summary: 'Reusable extraction schemas for structured web intelligence.',
  },
  {
    key: 'web_extraction_runs',
    label: 'Web Extraction Runs',
    dataType: 'web-extraction-runs',
    moduleKey: 'web_extraction_runs',
    summary: 'Recorded extraction outputs and confidence diagnostics.',
  },
];

export const INTELLIGENCE_SECTION_BY_KEY = Object.fromEntries(
  INTELLIGENCE_SECTIONS.map((section) => [section.key, section])
) as Record<IntelligenceSectionKey, IntelligenceSectionConfig>;

const SECTION_ALIASES: Record<string, IntelligenceSectionKey> = {
  clientprofiles: 'client_profiles',
  client_profiles: 'client_profiles',
  clientprofilesnode: 'client_profiles',
  competitors: 'competitors',
  searchresults: 'search_results',
  search_results: 'search_results',
  images: 'images',
  videos: 'videos',
  news: 'news',
  brandmentions: 'brand_mentions',
  brand_mentions: 'brand_mentions',
  mediaassets: 'media_assets',
  downloadedcontent: 'media_assets',
  downloaded: 'media_assets',
  media_assets: 'media_assets',
  searchtrends: 'search_trends',
  search_trends: 'search_trends',
  communityinsights: 'community_insights',
  community_insights: 'community_insights',
  aiquestions: 'ai_questions',
  ai_questions: 'ai_questions',
  websources: 'web_sources',
  web_sources: 'web_sources',
  websnapshots: 'web_snapshots',
  web_snapshots: 'web_snapshots',
  webrecipes: 'web_extraction_recipes',
  web_extraction_recipes: 'web_extraction_recipes',
  webextractionruns: 'web_extraction_runs',
  web_extraction_runs: 'web_extraction_runs',
};

const CRUD_ALIASES: Record<string, IntelligenceCrudAction> = {
  read: 'read',
  list: 'read',
  get: 'read',
  create: 'create',
  add: 'create',
  update: 'update',
  patch: 'update',
  delete: 'delete',
  remove: 'delete',
  clear: 'clear',
  reset: 'clear',
};

function normalize(value: unknown): string {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '');
}

export function resolveIntelligenceSection(raw: unknown): IntelligenceSectionKey | null {
  if (!raw) return null;
  const normalized = normalize(raw);
  if (!normalized) return null;
  return SECTION_ALIASES[normalized] || null;
}

export function resolveIntelligenceCrudAction(raw: unknown): IntelligenceCrudAction | null {
  if (!raw) return null;
  const normalized = normalize(raw);
  if (!normalized) return null;
  return CRUD_ALIASES[normalized] || null;
}
